#
# IMPORTANT: these configuration is only used for integration and unit testing purposes.
# It should be overriden by your own application when using this library.
#

ig_trading_api:
  account_number: "XXXXX"
  api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  auto_login: true
  base_url_demo: "https://demo-api.ig.com/gateway/deal"
  base_url_live: "https://api.ig.com/gateway/deal"
  execution_environment: "DEMO" # LIVE / DEMO
  password: "your_password"
  session_version: 2
  username: "your_username"
